version: '3.8'

services:
  user-management:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=order_management_system_db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - JWT_SECRET_KEY=your-production-secret-key-change-this
      - HOST=0.0.0.0
      - PORT=8001
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - order-management-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=order_management_system_db
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - order-management-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  order-management-network:
    driver: bridge
