version: '3.8'

services:
  app:
    build: .
    container_name: order-management-app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # Connect to XAMPP MySQL running on host machine
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/order_management_system_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - "8080:8080"
    restart: unless-stopped
    # Add extra_hosts for Linux/Mac compatibility
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
