version: '3.8'

services:
  app:
    build: .
    container_name: order-management-app
    environment:
      SPRING_PROFILES_ACTIVE: aws
      # These will be overridden by Beanstalk environment variables
      SPRING_DATASOURCE_URL: ${DB_URL:-jdbc:mariadb://localhost:3306/order_management_system_db?useSSL=true&serverTimezone=UTC}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-appuser}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-apppassword}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.mariadb.jdbc.Driver
      # AWS specific configurations
      SERVER_PORT: 5000
      JAVA_OPTS: "-Xmx512m -Xms256m"
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
